### ISSUE TITLE
trees with internal line breaks

### ISSUE THREAD

**Issue by kloetzl** [FePhyFoFum/phyx#55] opened 2017-02-23 10:15 UTC
pxbp segfaults on the attached file [29ecoli.txt](https://github.com/FePhyFoFum/phyx/files/796161/29ecoli.txt). Might be related to the extra line breaks.

Also happens with pxlstr

**Comment by jfwalker** [comment] 2017-02-23 10:23
Hi,

The line breaks are used to recognize if a file has multiple trees, since you only have one tree one option you do is to pipe the file is as follows
```
tr '\n' ' ' < 29ecoli.txt | pxbp
```
by piping the file it will automatically read it into pxbp or pxlstr so there is no need to specify the -t option, hope this helps!

**Comment by kloetzl** [comment] 2017-02-23 10:35
That works. But your parser should be able to recognize, that the tree is not done yet.

**Comment by josephwb** [comment] 2017-02-23 11:53
Hmm. I see the issue, and understand the logic, but how would such a tree be constructed? I am unaware of programs that generate trees with internal line breaks. There are many ways to make data messy; we certainly cannot support all. phyx was modelled based on processing _lines_. We can update the tree reader to consider this scenario (it currently expects a tree to line entirely within a single line), but I consider this very low priority given that we've never experienced it (and do not expect to in the future).

**Comment by kloetzl** [comment] 2017-02-23 11:57
> I see the issue, […] but how would such a tree be constructed?

PHYLIP :roll_eyes:

**Comment by josephwb** [comment] 2017-02-23 12:02
Really?!?

I still consider it very low priority then :bowtie:

**Comment by kloetzl** [comment] 2017-02-23 12:03
Yeah. Unfortunately, people still use that thing.

**Comment by kloetzl** [comment] 2017-02-23 12:16
Instead of a segfault you could print a 'unexpected line break in tree definition' error.

**Comment by josephwb** [comment] 2017-02-23 12:18
Yes, I was just teasing about phylip. Please do not destroy us Dr. Felsenstein.

Currently all ~40 programs assume a tree resides on a single line. To make things more general I've changed the title of this issue, and we'll come up with a solution (even if it is just to report an error).

**Comment by blackrim** [comment] 2017-03-27 18:44
I think I have a potential solution but will take a bit to implement. so not yet there.

**Comment by blackrim** [comment] 2017-12-16 03:57
The issue is whether we can assume that the last character is a `;`. If we can, then I can easily do this. If not, then I think it is a bit harder. What do you think @josephwb

**Comment by josephwb** [comment] 2017-12-16 10:53
I guess that would be how to do it. Personally I have never encountered a tree with an internal line break. But are trees even written without a `;`? Sounds safe.

**Comment by josephwb** [comment] 2021-04-17 23:35
Welp, 4 years later this is fixed with ec5527541308df38c13cbb6be955cdb89538356f. Yay?

**Closed by josephwb** 2021-04-17 23:35 UTC

**Comment by kloetzl** [comment] 2021-04-18 15:08
Better late than never. Thanks!
