### ISSUE TITLE
pxrr root with group as second preference

### ISSUE THREAD

**Issue by JimStarrett** [FePhyFoFum/phyx#95] opened 2019-01-24 05:11 UTC
Hello

Just curious if there is a way to root trees with a group of individuals as a second preference, as opposed to listing the individuals in the group. 

For example, if I had trees with taxa A-Z (with different missing taxa in different trees) and I preferred to root with A, but if A is missing in a tree then root with individuals B-E as a monophyletic group, what would be the command?

I have -g A,B,C,D,E  -r A,B,C,D,E but I want -g A,(B,C,D,E)

Thank you

**Comment by josephwb** [comment] 2019-01-24 08:03
Hmm. I _think_ the way to do it would be with 2 passes: 1) root on `-g B,C,D,E`, and 2) root on `-g A`. In the second pass, if A is not present, the tree from the first pass would be returned unaltered.

**Comment by JimStarrett** [comment] 2019-01-27 23:42
I tried this, and other things, but didn't seem to get the correct rooting. In fact, in many trees that had taxa A present, the rooting occurred elsewhere, at least when visualized with FigTree. The trees are in newick format, so I'm not sure why it is not recognizing taxa A.

**Comment by josephwb** [comment] 2019-01-27 23:55
Sorry for the headaches.

Could you please post such an example tree along with the `phyx` commands you are using? We'll get this sorted out.

**Comment by JimStarrett** [comment] 2019-01-28 00:48
No worries. I copied my command and an example of a good result followed by a bad result from rr_besttrees4.tre and the respective unrooted trees that they originated from in besttrees.tre.

pxrr -t besttrees.tre -g MY4366 -s -r MY4366,MY1173,MY1172,AR51,AR50,MY4258,AR92,AR93 -o rr_besttrees4.tre

From besttrees.tre
((AR84:0.00000100000050002909,(MY4226:0.00000100000050002909,(AR85:0.00000100000050002909,(((MY1034:0.00000100000050002909,(MY4213:0.00000100000050002909,MY4225:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,MY1060:0.00000100000050002909):0.00000100000050002909,((((MY977:0.00000100000050002909,((AR79:0.00000100000050002909,(AR78:0.00000100000050002909,MY4234:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,MY975:0.00000100000050002909):0.00000100000050002909):0.00387081964722365852,(((AR17:0.00387858678645839998,MY1046:0.00386230372152873052):0.00000100000050002909,(MY1014:0.00386243968720182806,(MY4366:0.01168834968464679477,((MY1163:0.00000100000050002909,((AR53:0.00000100000050002909,AR52:0.00000100000050002909):0.00000100000050002909,((MY4678:0.00387760282509805971,MY1164:0.00000100000050002909):0.00000100000050002909,((MY4258:0.00000100000050002909,((MY1173:0.00000100000050002909,AR51:0.00000100000050002909):0.00000100000050002909,(AR93:0.00000100000050002909,(MY1172:0.00000100000050002909,AR92:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00778265871515568947,MY4246:0.00778303900230808803):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,(((MY4251:0.00000100000050002909,(MY1318:0.00000100000050002909,MY409:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,MY4250:0.00000100000050002909):0.00388656481671631818,(MY4239:0.00000100000050002909,MY4238:0.00000100000050002909):0.00387830187604428943):0.00000100000050002909):0.00000100000050002909):0.00387035672506499473):0.00000100000050002909):0.00000100000050002909,((MY4204:0.00000100000050002909,(MY4203:0.00000100000050002909,AR64:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,(((MY1361:0.00000100000050002909,((((MY4209:0.00000100000050002909,MY405:0.00000100000050002909):0.00000100000050002909,MY4208:0.00000100000050002909):0.00000100000050002909,MY1161:0.00000100000050002909):0.00000100000050002909,MY4265:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,((((AR63:0.00000100000050002909,(((AR97:0.00000100000050002909,(AR31:0.00000100000050002909,AR27:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,(((((AR90:0.00000100000050002909,MY394:0.00000100000050002909):0.00000100000050002909,MY399:0.00000100000050002909):0.00000100000050002909,(((MY4217:0.00000100000050002909,MY4218:0.00000100000050002909):0.00387674761216754565,AR87:0.00000100000050002909):0.00000100000050002909,AR88:0.00000100000050002909):0.00000100000050002909):0.00388669768054033908,(MY1039:0.00000100000050002909,((MY1038:0.00000100000050002909,MY1148:0.00000100000050002909):0.00000100000050002909,MY4371:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00387871517803606552,(MY1149:0.00386229970816289250,((MY1157:0.00000100000050002909,(MY1158:0.00000100000050002909,AR55:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,AR56:0.00000100000050002909):0.00386229970595714737):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,MY1057:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,((MY1360:0.00000100000050002909,MY1160:0.00000100000050002909):0.00000100000050002909,AR83:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,((MY979:0.00000100000050002909,MY978:0.00000100000050002909):0.00000100000050002909,MY4210:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,AR98:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,(AR32:0.00000100000050002909,(MY1056:0.00000100000050002909,(AR18:0.00000100000050002909,(AR82:0.00000100000050002909,AR28:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00387858817827441919,(MY4221:0.00000100000050002909,AR75:0.00000100000050002909):0.00386229763313531392):0.00000100000050002909,MY1033:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,AR37:0.00000100000050002909,AR12:0.00000100000050002909):0.0;
(((((((((MY1034:0.00000100000050002909,MY986:0.00000100000050002909):0.00000100000050002909,(MY4226:0.00000100000050002909,MY1060:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,MY4246:0.00000100000050002909):0.00000100000050002909,MY1056:0.00000100000050002909):0.00000100000050002909,MY985:0.00000100000050002909):0.00000100000050002909,MY1059:0.00000100000050002909):0.00000100000050002909,MY1033:0.00000100000050002909):0.00000100000050002909,AR75:0.00000100000050002909):0.00000100000050002909,(AR78:0.00000100000050002909,(AR84:0.00000100000050002909,(MY1058:0.00000100000050002909,(((((((((MY1038:0.00000100000050002909,(AR18:0.00000100000050002909,MY4203:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,((MY1148:0.00000100000050002909,MY4204:0.00000100000050002909):0.00000100000050002909,(MY1014:0.00000100000050002909,MY1039:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,MY4371:0.00000100000050002909):0.00389258886230402267,(((MY4239:0.00000100000050002909,(MY4250:0.00000100000050002909,MY409:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,(MY1318:0.00000100000050002909,MY1317:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,(MY4251:0.00000100000050002909,(AR87:0.00000100000050002909,(MY1149:0.00000100000050002909,((((MY4217:0.00000100000050002909,AR91:0.00000100000050002909):0.00000100000050002909,((AR90:0.00000100000050002909,((MY394:0.00000100000050002909,MY399:0.00000100000050002909):0.00000100000050002909,MY1164:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,AR88:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,((AR17:0.00000100000050002909,(MY1163:0.00000100000050002909,MY4208:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,((AR52:0.00000100000050002909,AR53:0.00000100000050002909):0.00000100000050002909,(MY4218:0.00000100000050002909,MY4209:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,MY4210:0.00000100000050002909):0.00386050144529687198):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00386169741886135303,AR37:0.00000100000050002909):0.00000100000050002909,MY4221:0.00000100000050002909):0.00000100000050002909,((AR32:0.00000100000050002909,(AR56:0.00000100000050002909,(((MY4230:0.00000100000050002909,((MY1160:0.00000100000050002909,(MY1360:0.00000100000050002909,MY1361:0.00382002118368917091):0.00000100000050002909):0.00000100000050002909,((AR63:0.00384205834593303805,AR64:0.00000100000050002909):0.00000100000050002909,(MY4231:0.00000100000050002909,(((AR31:0.00000100000050002909,AR28:0.00000100000050002909):0.00000100000050002909,((AR15:0.00000100000050002909,MY1157:0.00000100000050002909):0.00000100000050002909,(((AR98:0.00000100000050002909,AR82:0.00000100000050002909):0.00000100000050002909,(AR83:0.00000100000050002909,(((AR48:0.00000100000050002909,((AR79:0.00000100000050002909,MY4234:0.00388491046991335225):0.00000100000050002909,MY978:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,(MY979:0.00000100000050002909,MY975:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,MY1046:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,(AR27:0.00000100000050002909,((MY4265:0.00000100000050002909,MY1161:0.00000100000050002909):0.00000100000050002909,MY405:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,(AR14:0.00000100000050002909,AR97:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00383809592419439563):0.00000100000050002909,MY1158:0.00000100000050002909):0.00000100000050002909,MY977:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,(((((AR92:0.00000100000050002909,AR51:0.00000100000050002909):0.00000100000050002909,AR50:0.00000100000050002909):0.00190038744504301255,AR93:0.00000100000050002909):0.00000100000050002909,MY4258:0.00000100000050002909):0.00189104007858236617,(MY4366:0.01187470177851479396,(MY1173:0.00038375100309218031,MY1172:0.00000100000050002909):0.00341197063039310865):0.00781939176327234482):0.00395071499987439349):0.00000100000050002909):0.00000100000050002909,AR55:0.00000100000050002909):0.00000100000050002909,((AR85:0.00000100000050002909,MY4225:0.00000100000050002909):0.00000100000050002909,MY4213:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,AR12:0.00000100000050002909):0.0;

From rr_besttrees4.tre
(MY4366:0.00584417484232339739,(((MY1163:0.00000100000050002909,((AR53:0.00000100000050002909,AR52:0.00000100000050002909):0.00000100000050002909,((MY4678:0.00387760282509805971,MY1164:0.00000100000050002909):0.00000100000050002909,((MY4258:0.00000100000050002909,((MY1173:0.00000100000050002909,AR51:0.00000100000050002909):0.00000100000050002909,(AR93:0.00000100000050002909,(MY1172:0.00000100000050002909,AR92:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00778265871515568947,MY4246:0.00778303900230808803):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,(((MY4251:0.00000100000050002909,(MY1318:0.00000100000050002909,MY409:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,MY4250:0.00000100000050002909):0.00388656481671631818,(MY4239:0.00000100000050002909,MY4238:0.00000100000050002909):0.00387830187604428943):0.00000100000050002909):0.00000100000050002909,(MY1014:0.00386243968720182806,((AR17:0.00387858678645839998,MY1046:0.00386230372152873052):0.00000100000050002909,(((MY4204:0.00000100000050002909,(MY4203:0.00000100000050002909,AR64:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,(((MY1361:0.00000100000050002909,((((MY4209:0.00000100000050002909,MY405:0.00000100000050002909):0.00000100000050002909,MY4208:0.00000100000050002909):0.00000100000050002909,MY1161:0.00000100000050002909):0.00000100000050002909,MY4265:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,((((AR63:0.00000100000050002909,(((AR97:0.00000100000050002909,(AR31:0.00000100000050002909,AR27:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,(((((AR90:0.00000100000050002909,MY394:0.00000100000050002909):0.00000100000050002909,MY399:0.00000100000050002909):0.00000100000050002909,(((MY4217:0.00000100000050002909,MY4218:0.00000100000050002909):0.00387674761216754565,AR87:0.00000100000050002909):0.00000100000050002909,AR88:0.00000100000050002909):0.00000100000050002909):0.00388669768054033908,(MY1039:0.00000100000050002909,((MY1038:0.00000100000050002909,MY1148:0.00000100000050002909):0.00000100000050002909,MY4371:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00387871517803606552,(MY1149:0.00386229970816289250,((MY1157:0.00000100000050002909,(MY1158:0.00000100000050002909,AR55:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,AR56:0.00000100000050002909):0.00386229970595714737):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,MY1057:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,((MY1360:0.00000100000050002909,MY1160:0.00000100000050002909):0.00000100000050002909,AR83:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,((MY979:0.00000100000050002909,MY978:0.00000100000050002909):0.00000100000050002909,MY4210:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,AR98:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,(AR32:0.00000100000050002909,(MY1056:0.00000100000050002909,(AR18:0.00000100000050002909,(AR82:0.00000100000050002909,AR28:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,((MY977:0.00000100000050002909,((AR79:0.00000100000050002909,(AR78:0.00000100000050002909,MY4234:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,MY975:0.00000100000050002909):0.00000100000050002909):0.00387081964722365852,((MY4221:0.00000100000050002909,AR75:0.00000100000050002909):0.00386229763313531392,(MY1033:0.00000100000050002909,(((MY1034:0.00000100000050002909,(MY4213:0.00000100000050002909,MY4225:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,MY1060:0.00000100000050002909):0.00000100000050002909,(AR85:0.00000100000050002909,(MY4226:0.00000100000050002909,(AR84:0.00000100000050002909,(AR37:0.00000100000050002909,AR12:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00387858817827441919):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00387035672506499473):0.00584417484232339739);
(((((((((MY1034:0.00000100000050002909,MY986:0.00000100000050002909):0.00000100000050002909,(MY4226:0.00000100000050002909,MY1060:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,MY4246:0.00000100000050002909):0.00000100000050002909,MY1056:0.00000100000050002909):0.00000100000050002909,MY985:0.00000100000050002909):0.00000100000050002909,MY1059:0.00000100000050002909):0.00000100000050002909,MY1033:0.00000100000050002909):0.00000100000050002909,AR75:0.00000100000050002909):0.00000100000050002909,(AR78:0.00000100000050002909,(AR84:0.00000100000050002909,(MY1058:0.00000100000050002909,(((((((((MY1038:0.00000100000050002909,(AR18:0.00000100000050002909,MY4203:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,((MY1148:0.00000100000050002909,MY4204:0.00000100000050002909):0.00000100000050002909,(MY1014:0.00000100000050002909,MY1039:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,MY4371:0.00000100000050002909):0.00389258886230402267,(((MY4239:0.00000100000050002909,(MY4250:0.00000100000050002909,MY409:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,(MY1318:0.00000100000050002909,MY1317:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,(MY4251:0.00000100000050002909,(AR87:0.00000100000050002909,(MY1149:0.00000100000050002909,((((MY4217:0.00000100000050002909,AR91:0.00000100000050002909):0.00000100000050002909,((AR90:0.00000100000050002909,((MY394:0.00000100000050002909,MY399:0.00000100000050002909):0.00000100000050002909,MY1164:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,AR88:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,((AR17:0.00000100000050002909,(MY1163:0.00000100000050002909,MY4208:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,((AR52:0.00000100000050002909,AR53:0.00000100000050002909):0.00000100000050002909,(MY4218:0.00000100000050002909,MY4209:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,MY4210:0.00000100000050002909):0.00386050144529687198):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00386169741886135303,AR37:0.00000100000050002909):0.00000100000050002909,MY4221:0.00000100000050002909):0.00000100000050002909,((AR32:0.00000100000050002909,(AR56:0.00000100000050002909,(((MY4230:0.00000100000050002909,((MY1160:0.00000100000050002909,(MY1360:0.00000100000050002909,MY1361:0.00382002118368917091):0.00000100000050002909):0.00000100000050002909,((AR63:0.00384205834593303805,AR64:0.00000100000050002909):0.00000100000050002909,(MY4231:0.00000100000050002909,(((AR31:0.00000100000050002909,AR28:0.00000100000050002909):0.00000100000050002909,((AR15:0.00000100000050002909,MY1157:0.00000100000050002909):0.00000100000050002909,(((AR98:0.00000100000050002909,AR82:0.00000100000050002909):0.00000100000050002909,(AR83:0.00000100000050002909,(((AR48:0.00000100000050002909,((AR79:0.00000100000050002909,MY4234:0.00388491046991335225):0.00000100000050002909,MY978:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,(MY979:0.00000100000050002909,MY975:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,MY1046:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,(AR27:0.00000100000050002909,((MY4265:0.00000100000050002909,MY1161:0.00000100000050002909):0.00000100000050002909,MY405:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,(AR14:0.00000100000050002909,AR97:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00383809592419439563):0.00000100000050002909,MY1158:0.00000100000050002909):0.00000100000050002909,MY977:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,(((((AR92:0.00000100000050002909,AR51:0.00000100000050002909):0.00000100000050002909,AR50:0.00000100000050002909):0.00190038744504301255,AR93:0.00000100000050002909):0.00000100000050002909,MY4258:0.00000100000050002909):0.00189104007858236617,(MY4366:0.01187470177851479396,(MY1173:0.00038375100309218031,MY1172:0.00000100000050002909):0.00341197063039310865):0.00781939176327234482):0.00395071499987439349):0.00000100000050002909):0.00000100000050002909,AR55:0.00000100000050002909):0.00000100000050002909,((AR85:0.00000100000050002909,MY4225:0.00000100000050002909):0.00000100000050002909,MY4213:0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909):0.00000100000050002909,AR12:0.00000100000050002909);

**Comment by JimStarrett** [comment] 2019-01-28 01:00
One other peculiar thing I noticed is that when I rooted a tree that had previously been rooted it returned only the trees (~800/3000) that included the individual I rooted with the second time (in my case MY4366). But that got me thinking that it would be nice if there was a command that could separate trees in a file to two files, one with trees that include an individual, and another file that includes all other trees. Then the rooting could be done separately and then combined afterward.

**Comment by josephwb** [comment] 2019-01-28 10:12
Okay, a couple of things. Outgroups should be given with `-g`. The `-r` command is simply a boolean to turn on ranking of those taxa specified with `-g`. Since `-r` does not take a value this _should_ throw some type of error. I will look into this. But as it stands, it will not work the way you hope with the command above. Sorry about this. I will update the help.

As for the error (only the trees that included the individual) this can be overridden with the `-s` argument. Without it, an error is written to sterr:
```
pxrr -t besttrees.tre -g FAKE
Taxon 'FAKE' not found in tree.
the outgroup taxa don't exist in this tree
```
but produces no output. With `-s` ("silent error") the original tree is returned unaltered. So the procedure above _should_ work. Hmm I see that you have `-s` above; did you perhaps omit it from the second round of rooting?

As for separating the trees into multiple files, this can be done on the command line. Say we are interested in trees that have taxon `AR14` and those that do not. You can do:
```
grep AR14 besttrees.tre > present.trees
grep -v AR14 besttrees.tre > present.trees
```
You can use other tools like awk or sed, but I know that at least the latter has different syntax on linux vs. mac.

**Comment by josephwb** [comment] 2019-01-28 10:33
@JimStarrett can you retry things with the `-r` args moved to `-g` and making sure `-s` is present? So:
```
pxrr -t besttrees.tre -g MY4366,MY1173,MY1172,AR51,AR50,MY4258,AR92,AR93 -s -r -o rr_besttrees4.tre
```
No need to pull/recompile as I have not made any edits yet (other than to the help).

**Comment by JimStarrett** [comment] 2019-01-28 22:52
Sorry about misinterpreting the -r flag. I'm still hitting a small snag on the two-step rooting though.

As expected, when I use the following command I get trees consistently rooted with MY4366, and if MY4366 is not present then rooted by one or more of the remaining taxa:

pxrr -t besttrees.tre -g MY4366,MY1173,MY1172,AR51,AR50,MY4258,AR92,AR93 -s -r -o rr_besttrees5.tre


However, if MY4366 is not present I would like to root with MY1173,MY1172,AR51,AR50,MY4258,AR92,AR93 as a group. So I tried to the two-step rooting, first running the following command to root with the group:

pxrr -t besttrees.tre -g MY1173,MY1172,AR51,AR50,MY4258,AR92,AR93 -s -o rr_NorCo_besttrees5.tre

As far as I can tell, everything rooted properly.

Then, I attempted to root those resulting trees (rr_NorCo_besttrees5.tre) with MY4366 with the following command:

pxrr -t rr_NorCo_besttrees5.tre -g MY4366 -s -o rr_MontNorCo_besttrees4.tre

Unfortunately, this resulted in one tree rooted with MY4366 and the others not, even though MY4366 was present. The first tree in the file is properly rooted with MY4366, but looking at the next 50 trees or so I did not see any rooted with MY4366 even when it was clearly present. So it seems that the program is bugging out after reading the first tree file, or when it comes across a tree with MY4366 absent, even though I had the -s flag in the command.

**Comment by josephwb** [comment] 2019-01-29 09:44
Ok this _sounds_ like it might be the line-endings issue? What if you extract the second tree and try to root that with MY4366? But that doesn't really make sense if the input to the second round was _produced_ by `phyx` (i.e., they should be unix line endings)...

Perhaps you can send me the original file directly (phylo.jwb AT gmail). Or just the first 10 trees or so.

**Comment by josephwb** [comment] 2019-01-29 16:07
I believe this is fixed. Please do:
```
git pull && make pxrr && sudo make install
```

**Comment by JimStarrett** [comment] 2019-01-29 17:42
It appears that I'm running into errors when installing the program that may be the cause of the rooting issue. I ran the commands in build from source with homebrew:

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install git cmake nlopt armadillo
git clone https://github.com/FePhyFoFum/phyx.git
cd phyx/src
./configure
make
python run_tests.py

There were errors detected after running make and the python run test.

From make:
./optimize_state_reconstructor_nlopt.h:11:10: fatal error: 'nlopt.h' file not found

From python run_tests.py:
PASSED TESTS: 26
FAILED TESTS: 8
These failed:
	pxmrcacut,pxmrcaname,pxrlt,pxrmk,pxrmt,pxrr,pxt2new,pxtscale

**Comment by josephwb** [comment] 2019-01-29 18:23
Ok, the nlopt one is confusing as you seemed to have installed it? Unfortunately I do not have a mac to test on. What does this do:
```
brew install git nlopt
```
Any errors/warnings?

The other errors are all ok. We changed the precision of the edge lengths, so the "errors" are just extra decimal places.

**Comment by JimStarrett** [comment] 2019-01-29 18:33
When I run: 

brew install git nlopt

It shows:

Linking /usr/local/Cellar/nlopt/2.4.2_2... 
Error: Could not symlink lib/python2.7/site-packages/_nlopt.0.so
/usr/local/lib/python2.7/site-packages is not writable.

Sorry the mac issue is being so stubborn!

**Comment by josephwb** [comment] 2019-01-29 18:40
Oof. Phyx comes with a version of nlopt (in the `deps` directory), but that might not be what you want to do. Maybe @blackrim can help?

**Comment by blackrim** [comment] 2019-01-29 19:02
Hm, I am not sure. that sounds like a homebrew error. 
Something like this might help?
https://stackoverflow.com/questions/14527521/brew-doctor-says-warning-usr-local-include-isnt-writable

**Comment by josephwb** [comment] 2019-01-29 20:17
Yeah, that sounds right. Perhaps there was a `sudo brew` in the past?

(FWIW I am guilty of `sudo pip install` 99.98% of the time. Ok, maybe 100%...)

**Comment by josephwb** [comment] 2019-01-29 21:37
Good to hear this. Although your issues (nlopt) were not the cause of the errors you came across. Please rerun the `pxrr` commands to determine that things have indeed been fixed on our end.

**Comment by JimStarrett** [comment] 2019-01-30 02:30
Ok, it is working, sort of...at least, I could certainly work with these results if needed. 

I ran:
 pxrr -t besttrees.tre -g MY1173,MY1172,AR51,AR50,MY4258,AR92,AR93 -s -o rr_NorCo_besttrees7.tre

It returned a file with 9 trees and these seem to mostly be rooted with the group as monophyletic, but there should actually be 3368 trees. Then I ran the same command but included the -r flag, which resulted in 3368 trees.

pxrr -t besttrees.tre -g MY1173,MY1172,AR51,AR50,MY4258,AR92,AR93 -s -r -o rr_NorCo_besttrees8.tre

However, the trees appear to be rooted with MY1173 (or other single taxa) rather than as a monophyletic group, even when all seven taxa are present. 

The good news is that the second rooting, with the command below, resulted in the correct MY4366 root when MY4366 was present (All 3368 trees are returned). If MY4366 was not present then it would maintain the rooting from before (ie with the group not being monophyletic).

pxrr -t rr_NorCo_besttrees8.tre -g MY4366 -s -o rr_MontNorCo_besttrees7.tre


If this is occupying too much of your time we can certainly set it aside or I could try your grep method of separating the trees and then rooting them separately. I don't want to bog you down so just let me know! Thanks.

**Comment by josephwb** [comment] 2019-01-30 08:09
So when `-r` is used, all trees should be returned with a single outgroup (it roots on the first found in the list). This is useful when you have successive outgroups (maybe not so much if your outgroups are monophyletic). So that makes sense.

I don't understand the first result (only 9 trees produced). Can you send me that file.

Sorry this is such a pain.

**Comment by JimStarrett** [comment] 2019-01-30 22:45
Hi Joseph

I've attached the original tree file, and the resulting tree file with 9
trees. Here is the command:

pxrr -t besttrees.tre -g MY1173,MY1172,AR51,AR50,MY4258,AR92,AR93 -s -o
rr_NorCo_besttrees7.tre


thank you for taking a look

Jim

**Comment by josephwb** [comment] 2019-01-31 16:10
@JimStarrett can you try:
```
git pull && make pxrr && sudo make install
```

**Comment by JimStarrett** [comment] 2019-01-31 20:21
When I run:
git pull && make pxrr && sudo make install

it returns:
fatal: not a git repository (or any of the parent directories): .git

when I run:
git clone https://github.com/FePhyFoFum/phyx.git

it returns:
fatal: destination path 'phyx' already exists and is not an empty directory.

Also, when I run: 
autoreconf -fi

it returns:
-bash: autoreconf: command not found

Not sure what to make of these messages, I may have made it all out of sorts at this point.

**Comment by JimStarrett** [comment] 2019-02-07 05:55
Sorry for the late reply. It looks like it's doing exactly what I want now. Thank you!

**Comment by josephwb** [comment] 2019-02-22 12:15
Closing as I gather this is working as expected.

**Closed by josephwb** 2019-02-22 12:15 UTC
